version: '3.7'

services:
  app:
    image: registry.gitlab.tpwd.de/tpwd/bb-navi/datahub-json2graphql
    networks:
      public:
      bbnavi-json2graphql-db:
    depends_on: [db]
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    configs:
      - source: bbnavi-json-2-graphql-master-key
        target: /app/config/master.key
      - source: bbnavi-json-2-graphql-master-key
        target: /app/config/credentials/production.key
    volumes:
      - unicorn:/unicorn
      - assets:/assets
    deploy:
      labels:
        traefik.docker.network: public
        traefik.enable: "true"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.redirect.entryPoint: https
        traefik.frontend.rule: Host:json.datahub.bbnavi.de
        traefik.port: '80'
      restart_policy:
        condition: on-failure

  db:
    image: 'postgres:10.3-alpine'
    environment:
      POSTGRES_USER: bbnavi
      POSTGRES_PASSWORT: bbnavi
      POSTGRES_DB: bbnavi
    volumes:
      - json_db:/var/lib/postgresql/data
    networks:
      bbnavi-json2graphql-db:
        aliases:
          - bbnavi-json2graphql-db
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  json_db:
  unicorn:
  assets:

configs:
  bbnavi-json-2-graphql-master-key:
    external: true

networks:
  public:
    external: true
  bbnavi-json2graphql-db:
    external: true
